<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ifm.IoTCore" Version="7.0.0" />
    <PackageReference Include="ifm.IoTCore.MessageConverter.Json" Version="6.1.1" />
    <PackageReference Include="ifm.Logger" Version="1.1.5" />
    <PackageReference Include="ifm.DataStore" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\source\ifm.IoTCore.NetAdapter.Http.Profile.HttpServer\ifm.IoTCore.NetAdapter.Http.Profile.HttpServer.csproj" />
    <ProjectReference Include="..\..\source\ifm.IoTCore.NetAdapter.Http.Server\ifm.IoTCore.NetAdapter.Http.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
