<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyVersion>4.2.0</AssemblyVersion>
    <Version>4.2.0</Version>
    <Company>ifm ecomatic gmbh</Company>
    <Product>ifm IoT-Core</Product>
    <Description>The package contains the IoT-Core HTTP server network adapter.</Description>
    <Copyright>Copyright © ifm ecomatic gmbh. All rights reserved.</Copyright>
    <Authors>ESI Middleware</Authors>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <Nullable>enable</Nullable>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt" />
    <None Include="..\..\NOTICE.md" Pack="true" PackagePath="NOTICE.md" />
  </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\ifm.datastore\ifm.DataStore.Contracts\ifm.DataStore.Contracts.csproj" />
        <ProjectReference Include="..\..\..\ifm.iotcore\source\ifm.IoTCore.Common\ifm.IoTCore.Common.csproj" />
        <ProjectReference Include="..\..\..\ifm.iotcore\source\ifm.IoTCore.MessageConverter.Contracts\ifm.IoTCore.MessageConverter.Contracts.csproj" />
        <ProjectReference Include="..\..\..\ifm.iotcore\source\ifm.IoTCore.MessageDispatcher.Contracts\ifm.IoTCore.MessageDispatcher.Contracts.csproj" />
        <ProjectReference Include="..\..\..\ifm.iotcore\source\ifm.IoTCore.NetAdapter.Contracts\ifm.IoTCore.NetAdapter.Contracts.csproj" />
        <ProjectReference Include="..\..\..\ifm.logger\ifm.Logger.Contracts\ifm.Logger.Contracts.csproj" />
        <ProjectReference Include="..\ifm.IoTCore.NetAdapter.Http.Contracts\ifm.IoTCore.NetAdapter.Http.Contracts.csproj" />
    </ItemGroup>
</Project>