<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyVersion>7.0.0</AssemblyVersion>
		<Version>7.0.0</Version>
		<Company>ifm ecomatic gmbh</Company>
		<Product>ifm IoT-Core</Product>
		<Description>The package contains the IoT-Core interface.</Description>
		<Copyright>Copyright © ifm ecomatic gmbh. All rights reserved.</Copyright>
		<Authors>ESI Middleware</Authors>
		<LangVersion>latest</LangVersion>
		<IsPackable>true</IsPackable>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<DebugType>embedded</DebugType>
		<EmbedAllSources>true</EmbedAllSources>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(CI_BUILD)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\LICENSE.txt" Pack="true" PackagePath="." />
		<None Include="..\..\NOTICE.md" Pack="true" PackagePath="." />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\ifm.datastore\ifm.DataStore.Contracts\ifm.DataStore.Contracts.csproj" />
		<ProjectReference Include="..\..\..\ifm.logger\ifm.Logger.Contracts\ifm.Logger.Contracts.csproj" />
		<ProjectReference Include="..\ifm.IoTCore.ElementManager.Contracts\ifm.IoTCore.ElementManager.Contracts.csproj" />
		<ProjectReference Include="..\ifm.IoTCore.EventSender.Contracts\ifm.IoTCore.EventSender.Contracts.csproj" />
		<ProjectReference Include="..\ifm.IoTCore.MessageDispatcher.Contracts\ifm.IoTCore.MessageDispatcher.Contracts.csproj" />
		<ProjectReference Include="..\ifm.IoTCore.NetAdapterManager.Contracts\ifm.IoTCore.NetAdapterManager.Contracts.csproj" />
		<ProjectReference Include="..\ifm.IoTCore.PersistenceManager.Contracts\ifm.IoTCore.PersistenceManager.Contracts.csproj" />
		<ProjectReference Include="..\ifm.IoTCore.UserManager.Contracts\ifm.IoTCore.UserManager.Contracts.csproj" />
	</ItemGroup>
</Project>
