<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AssemblyVersion>6.1.1</AssemblyVersion>
		<Version>6.1.1</Version>
		<Company>ifm ecomatic gmbh</Company>
		<Product>ifm IoT-Core</Product>
		<Description>The package contains the IoT-Core JSON message converter class.</Description>
		<Copyright>Copyright © ifm ecomatic gmbh. All rights reserved.</Copyright>
		<Authors>ESI Middleware</Authors>
		<LangVersion>latest</LangVersion>
		<IsPackable>true</IsPackable>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<DebugType>embedded</DebugType>
		<EmbedAllSources>true</EmbedAllSources>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(CI_BUILD)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\LICENSE.txt" Pack="true" PackagePath="." />
		<None Include="..\..\NOTICE.md" Pack="true" PackagePath="." />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ifm.IoTCore.Common\ifm.IoTCore.Common.csproj" />
		<ProjectReference Include="..\ifm.IoTCore.MessageConverter.Contracts\ifm.IoTCore.MessageConverter.Contracts.csproj" />
	</ItemGroup>
</Project>
